export const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SELECTED_MOVIE_SHOW: 'SELECTED_MOVIE_SHOW',
    REMOVE_SELECTED_MOVIE_SHOW: 'REMOVE_SELECTED_MOVIE_SHOW',
    SET_SHOWS: 'SET_SHOWS',
    SET_STAT:'SET_STAT'
};
